version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twitter_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  message-service:
    build: ./message-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres

  like-service:
    build: ./like-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres

volumes:
  db-data:
